In [4]:
import numpy as np

# create a numpy array
aArr = np.array([x for x in range(1,6)])
print('aArr: ', aArr)
print('dtype: ', aArr.dtype)
print('shape: ', aArr.shape)

aArr:  [1 2 3 4 5]
dtype:  int64
shape:  (5,)


In [5]:
# Create a rank 1 ndarray from a Python list that contains integers and strings
bArr = np.array([1, 2, 'World'])
print('bArr: ', bArr)
print('bArr type: ', type(bArr))
print('dtype: ', bArr.dtype)
print('shape: ', bArr.shape)

bArr:  ['1' '2' 'World']
bArr type:  <class 'numpy.ndarray'>
dtype:  <U21
shape:  (3,)


In [8]:
# Create a rank 1 ndarray that contains floats
c = np.array([1.0,2.0,3.0, 88])
print('bArr: ', c)
print('bArr type: ', type(c))
print('dtype: ', c.dtype)
print('shape: ', c.shape)


bArr:  [  1.   2.   3.  88.]
bArr type:  <class 'numpy.ndarray'>
dtype:  float64
shape:  (4,)


In [12]:
# Create a rank 1 ndarray of floats but set the dtype to int64
d = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)
print('bArr: ', d)
print('bArr type: ', type(d))
print('dtype: ', d.dtype)
print('shape: ', d.shape)

bArr:  [1 2 3 4 5]
bArr type:  <class 'numpy.ndarray'>
dtype:  int64
shape:  (5,)


In [13]:
# create a rank 1 ndarray
e = np.array([1, 2, 3, 4, 5])

# save x into the current directory as 
np.save('my_array', e)

# load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# print y
print()
print('y = ', y)
print()



y =  [1 2 3 4 5]



## Using Numpy build-in funcitons to create ndarray

In [27]:
# create a 3 x 4 ndarray full of zeros. 
f = np.zeros((3,4))
print()
print('f= \n', f)
print()
print('shape: ', f.shape)
print('type: ', type(f))
print('dtype ', f.dtype)

# specify data type
h = np.zeros((3,4), dtype=int)
print()
print('h= \n', h)
print()

g = np.ones((3,4), dtype=int)
print('g=\n', g)


f= 
 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

shape:  (3, 4)
type:  <class 'numpy.ndarray'>
dtype  float64

h= 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

g=
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [29]:
# create ndarray with a specified shape that is full of any value
full = np.full((2, 3), 5.)
print('full=\n ', full)

full=
  [[ 5.  5.  5.]
 [ 5.  5.  5.]]


In [31]:
# np.eye(N) creates a square N x N ndarray corresponding to the Identity matrix.
eye = np.eye(6)
print('eye=\n', eye)

eye=
 [[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


In [32]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
diag = np.diag([10,20,30,50])
print('diag=\n', diag)

diag=
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [33]:
# Create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
rangeArr = np.arange(1,14,3)
print('rangeArr= \n', rangeArr)

rangeArr= 
 [ 1  4  7 10 13]


In [36]:
# Create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.(endpoint=False)
arrLin = np.linspace(0,25,10, endpoint = False)
print('arrLin=\n', arrLin)

arrLin=
 [  0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5]


In [52]:

ndArrRandom = np.random.random((3,6)).reshape(9,2)
# np.random.randint(start, stop, size = shape)

In [53]:
print(ndArrRandom)

[[ 0.73936556  0.66384373]
 [ 0.85662217  0.56969913]
 [ 0.56106364  0.63945219]
 [ 0.73786784  0.29017251]
 [ 0.49840871  0.761671  ]
 [ 0.53106127  0.53302715]
 [ 0.15776216  0.31086511]
 [ 0.59109853  0.51998414]
 [ 0.30284665  0.92565337]]


In [61]:
# create ndarrays with random numbers that satisfy certain statistical properties
# np.random.normal(mean, standard deviation, size=shape)
# create a 100 x 100 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
ndArrNor = np.random.normal(0, 0.1, size=(100,100))
print('ndArrNor = \n', ndArrNor)
print()
print('shape: ',ndArrNor.shape )
print('dtype: ', ndArrNor.dtype)
print('type: ', type(ndArrNor))
print('max: ', ndArrNor.max())
print('min: ', ndArrNor.min())
print('mean: ', ndArrNor.mean())
print('negative number: ', (ndArrNor < 0).sum())
print('positive number: ', (ndArrNor > 0).sum())

ndArrNor = 
 [[-0.15935002  0.14302032 -0.00764631 ...,  0.11881185  0.19292268
  -0.08987834]
 [ 0.13407518  0.10124731 -0.14720596 ...,  0.03673544  0.09312499
  -0.19463469]
 [-0.08727059 -0.01653929 -0.08956294 ...,  0.24731355 -0.26985312
   0.17146987]
 ..., 
 [ 0.00977421  0.00893021 -0.21083963 ..., -0.05928638 -0.0821532
  -0.09201788]
 [ 0.01664932  0.08131947  0.0842149  ...,  0.09589863 -0.12421034
  -0.01263083]
 [ 0.04701478  0.01441019  0.22063747 ...,  0.18935602 -0.06392775
   0.0229201 ]]

shape:  (100, 100)
dtype:  float64
type:  <class 'numpy.ndarray'>
max:  0.366859087332
min:  -0.386646828783
mean:  0.000192250508953
negative number:  4954
positive number:  5046


In [60]:
tem = np.array([1,2,5,6,4,0,-9])
tem  > 0

array([ True,  True,  True,  True,  True, False, False], dtype=bool)

## Mutate ndarray


In [71]:
# create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
ndarrMu = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [72]:
# delete the first row of y
w = np.delete(ndarrMu, 0, axis=0)

# delete the first and last column of y
v = np.delete(ndarrMu, [0,2], axis=1)


In [73]:
print(w)

[[4 5 6]
 [7 8 9]]


In [74]:
print(v)

[[2]
 [5]
 [8]]


In [75]:
print(ndarrMu)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
# append a new row containing 7,8,9 to y
newNdArr1 = np.append(ndarrMu, [[7,8,9]], axis=0)

# append a new column containing 9 and 10 to y
newNdArr2 = np.append(ndarrMu,[[9],[10],[11]], axis=1)

print(newNdArr1)
print()
print(newNdArr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]

[[ 1  2  3  9]
 [ 4  5  6 10]
 [ 7  8  9 11]]


In [79]:
# np.insert(ndarray, index, elements, axis)
# np.vstack()
# np.hstack()

# Slicing ndarray

In [80]:
ndarrSlicing = np.arange(20).reshape(5,4)
print(ndarrSlicing)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [83]:
s1 = ndarrSlicing[1:4,2:5]
print(s1)
s1[0,0] = 89 # this will change ndarrSlicing as well, because ndarray slicing is a view of original array


[[89  7]
 [10 11]
 [14 15]]


In [84]:
print(ndarrSlicing)

[[ 0  1  2  3]
 [ 4  5 89  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [88]:
# to create a new ndarray that contains a copy of the values in the slice we need to use the np.copy()
s2 = ndarrSlicing[1:4,2:5].copy()
s2[0,0] = 100
print(s2)
print()
print(ndarrSlicing)

[[100   7]
 [ 10  11]
 [ 14  15]]

[[ 0  1  2  3]
 [ 4  5 89  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [91]:
# to extract only the unique elements in an ndarray
np.unique(np.random.random((3,5)))

array([ 0.0056741 ,  0.06455062,  0.09918317,  0.16731196,  0.18720107,
        0.23805154,  0.27650698,  0.30374367,  0.40049867,  0.54028808,
        0.61422525,  0.65164235,  0.77319267,  0.86279759,  0.94131908])

In [93]:
ndUnique = np.unique([[1,2,3],[5,2,8],[1,2,3]])
print(ndUnique)
print('type: ', type(ndUnique))


[1 2 3 5 8]
type:  <class 'numpy.ndarray'>


## Extracts the elements along the diagonal

In [96]:
# np.diag(ndarray, k=N)
# default k = 0
# k < 0, select elements in diagonal below main diagonal
# k > 0, select elemnts in diagonal above main diagonal
ndarrDiag = np.arange(25).reshape(5,5)
print(ndarrDiag)
print()
print(np.diag(ndarrDiag))
print()
print(np.diag(ndarrDiag, k=1))
print()
print(np.diag(ndarrDiag, k=-1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[ 0  6 12 18 24]

[ 1  7 13 19]

[ 5 11 17 23]


## Boolean indexing, sorting, set operations

In [100]:
ndarrayB = np.random.randint(1, 25,size=(5,5))
print(ndarrayB)
print()
print('Values are greater than 7 and less than 12 in ndarayB: ', ndarrayB[(ndarrayB > 7) & (ndarrayB < 12)])

[[12 23 20 19  2]
 [15 23  6 22  2]
 [21  9  6 18  8]
 [21 12 16  4 16]
 [ 1  4  1 15 11]]

Values are greater than 7 and less than 12 in ndarayB:  [ 9  8 11]


In [101]:
ndarrS1 = np.arange(12)
ndarrS2 = np.arange(3,26)
print()
print('The elements that are both in ndarrS1 and ndarrS2:', np.intersect1d(ndarrS1,ndarrS2))
print('The elements that are in ndarrS1 that are not in ndarrS2:', np.setdiff1d(ndarrS1,ndarrS2))
print('All the elements of ndarrS1 and ndarrS2:',np.union1d(ndarrS1,ndarrS2))



The elements that are both in ndarrS1 and ndarrS2: [ 3  4  5  6  7  8  9 10 11]
The elements that are in ndarrS1 that are not in ndarrS2: [0 1 2]
All the elements of ndarrS1 and ndarrS2: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [110]:
# sorting rank 2 ndarrays, specify to the np.sort() function whether we are sorting by rows or columns. This is done by using the axis keyword
ndSorting = np.random.randint(4,89, size=(5,4))
print(ndSorting)
print()
print('ndSorting with sorted rows:\n ', np.sort(ndSorting, axis=1))
print()
print('ndSorting with sorted column:\n ', np.sort(ndSorting, axis=0))



[[50 15  4 13]
 [22  5 79 72]
 [24 66 84 55]
 [88 24 66 52]
 [41 36 31 38]]

ndSorting with sorted rows:
  [[ 4 13 15 50]
 [ 5 22 72 79]
 [24 55 66 84]
 [24 52 66 88]
 [31 36 38 41]]

ndSorting with sorted column:
  [[22  5  4 13]
 [24 15 31 38]
 [41 24 66 52]
 [50 36 79 55]
 [88 66 84 72]]


## Arithmetic operation and broadcasting
- [broadcasting rules](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

In [124]:
ndarrAri = np.arange(2,45,5)
ndarrAri2 = np.arange(1,44,5)
print(ndarrAri)
print()
print(ndarrAri2)
print()
print(ndarrAri + ndarrAri2)
print()
print(ndarrAri - ndarrAri2)
print()
print(ndarrAri * ndarrAri2)
print()
print(ndarrAri // ndarrAri2)

[ 2  7 12 17 22 27 32 37 42]

[ 1  6 11 16 21 26 31 36 41]

[ 3 13 23 33 43 53 63 73 83]

[1 1 1 1 1 1 1 1 1]

[   2   42  132  272  462  702  992 1332 1722]

[2 1 1 1 1 1 1 1 1]


In [139]:
ndarr2D = np.array([ndarrAri.copy(), ndarrAri2.copy()])[:,:3]
print(ndarr2D)
print()
print('ndarr2D mean: ',ndarr2D.mean())
print()
print('ndarr2D mean x: ',ndarr2D.mean(axis=1))
print()
print('ndarr2D mean y: ',ndarr2D.mean(axis=0))
print()
print('ndarr2D std : ',ndarr2D.std())
print()
print('ndarr2D std y: ',ndarr2D.std(axis=0))
print()
print('ndarr2D sum : ',ndarr2D.sum(axis=0))
print()


[[ 2  7 12]
 [ 1  6 11]]

ndarr2D mean:  6.5

ndarr2D mean x:  [ 7.  6.]

ndarr2D mean y:  [  1.5   6.5  11.5]

ndarr2D std :  4.11298755975

ndarr2D std y:  [ 0.5  0.5  0.5]

ndarr2D sum :  [ 3 13 23]



In [143]:
np.ones((4,4),dtype=int)*(np.arange(1,5))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [144]:
np.arange(1,5)

array([1, 2, 3, 4])